### PR TITLE
Fix unspoken meaning translation

### PR DESCRIPTION
**Pull request by BenjaminChenTW**

### CODE REVIEW

**Comment by gioxx** [comment]
Please don't touch messages.json files (except for English) because all translations are managed by Crowdin (https://crowdin.com/project/tms).

If you want to propose a new string you can add that in https://github.com/gioxx/MarvellousSuspender/blob/master/src/_locales/en/messages.json (is the "master file" that Crowdin uses for translation into other languages), I have already seen that you are actively participating on Crowdin, at this point I am closing this merge. Please propose a new merge to modify the gitignore file ;-)

**Comment by BenjaminChenTW** [comment]
@gioxx This is my first time working with Crowdin. Sorry about the mistake 🤦. I've created a new pull request ( #64  ) to modify the gitignore file. Please check it out.

**Comment by BenjaminChenTW** [comment]
@gioxx I've just created a new pull request ( #68 ) to add a new string. Please check it out also. If there is any problem, please let me know.

**Comment by gioxx** [comment]
@BenjaminChenTW you don't have to worry at all, rather, thank you so much for your amazing work!

**Pull request closed without merging**
