### PR TITLE
Proposed Change: The Marvellous Suspender is about to get marvellous-er

### PR DESCRIPTION
**Pull request by cholladay0816**
This is just a funny idea I had after seeing the latest update message, feel free to close if it doesn't work for you.

### CODE REVIEW

**Comment by calumapplepie** [comment]
"More Marvelous" is a nice alternative, as well.

**Comment by 1Mgtrn3** [comment]
Omg, the update popup is extremely annoying. I don't want to see it 5 times a day, interrupting me from my work, switching the focus to its tab. Can we do something about it? Honestly, after it being such an annoyance I seriously think about what's inside that update. I don' want this extension to repeat what the previous "version" did.

**Comment by calumapplepie** [comment]
Were it not for that update popup, the previous version's malware would never have been discovered.

If it annoys you that much, just let it update.  It's not hard.  There's no reason to make a big thing out of it.

**Review by napolux — APPROVED** [review]

**Comment by Technetium1** [comment]
> "More Marvelous" is a nice alternative, as well.

That would be the grammatically correct choice. It's hard to support intentional misspelling.

@1Mgtrn3 You can simply navigate to `chrome://restart` and carry on with your work.

**Review by napolux — APPROVED** [review]

**Pull request merged**
